### ISSUE TITLE
What is wrong from my side

### ISSUE THREAD

**Issue by vgul** [s0ftik3/reverso-api#14]
Hi
What is wrong

```
locate reverso.js  | xargs ls -lt
-rw-r--r-- 1 vlad vlad 12569 Oct 26  1985 /home/vlad/misc/node_modules/reverso-api/src/reverso.js
-rw-r--r-- 1 vlad vlad 12569 Oct 26  1985 /home/vlad/node_modules/reverso-api/src/reverso.js
-rw-r--r-- 1 vlad vlad 12569 Oct 26  1985 /usr/local/lib/node_modules/reverso-api/src/reverso.js
```

```
cat ./r.js 


import { Reverso } from 'reverso-api'
const reverso = new Reverso()
```

```
node ./r.js 
(node:39935) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/home/vlad/misc/r.js:3
import { Reverso } from 'reverso-api'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

Sorry, Im not experiencied in nodejs

**Comment by s0ftik3** [comment]
use commonjs to import the module, fixed
